In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df=pd.read_csv("banglore_h.csv")

In [7]:
df

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...   
1                       0                           1  ...   
2                       0                           1  ...   
3                       0                           1  ...   
4                       1                           1  ...   
...                   ...                         ...  ...   
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1                             0                    0   
2                             0                    0   
3                             0                    0   
4

In [4]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [5]:
df.tail()

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
7115                          0                    0   
7116                          0                    0   
7117                          0                    0   
7118                          0                    0   
7119                          0                    0   

      location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
7115                            0                0                     0   
7116                            0                0                     0   
7117                            0                0                     0   
7118                            0                0                     0   
7119                            0                0                     0   

      location_Tumkur Road  
7115                     0  
7116                     0  
7117                     0  
7118                     0  
7119                     0  

[5 rows x 108 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Columns: 108 entries, bath to location_Tumkur Road
dtypes: float64(5), int64(103)
memory usage: 5.9 MB


In [7]:
 df.isnull().sum()

bath                           0
balcony                        0
price                          0
total_sqft_int                 0
bhk                            0
                              ..
location_Hosur Road            0
location_Horamavu Banaswadi    0
location_Domlur                0
location_Mahadevpura           0
location_Tumkur Road           0
Length: 108, dtype: int64

In [8]:
df.isnull().any()

bath                           False
balcony                        False
price                          False
total_sqft_int                 False
bhk                            False
                               ...  
location_Hosur Road            False
location_Horamavu Banaswadi    False
location_Domlur                False
location_Mahadevpura           False
location_Tumkur Road           False
Length: 108, dtype: bool

In [9]:
### split data ###
X=df.drop('price',axis=1)
y=df['price']

In [10]:
print("X of shape",X.shape)
print("y of shape",y.shape)


X of shape (7120, 107)
y of shape (7120,)


In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=50)

In [12]:
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)
 

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


In [14]:
    ### Feature Scalling ###
    from sklearn.preprocessing import StandardScaler
    sc=StandardScaler()
    sc.fit(X_train)
    X_train=sc.transform(X_train)
    X_test=sc.transform(X_test)

In [16]:
## Linear regression ##
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [20]:
lr.fit(X_train,y_train)

LinearRegression()

In [24]:
### coffecient of features models
lr.coef_

array([ 4.96061905e-01, -8.01167316e-02,  7.91448451e+01, -9.63563893e+00,
        6.31774024e+01, -6.38257260e-01, -1.89944708e+00, -3.64060273e+00,
       -1.05956057e+00, -3.21472072e+00, -2.37479962e+00,  3.99282257e-01,
       -1.12268530e+00,  1.83354966e+00,  2.08184750e-01, -1.38264110e+00,
       -2.52761801e-01,  2.19953858e+00, -1.45469773e+00,  1.72049601e+00,
       -2.59544613e+00, -1.49092982e+00, -8.44547973e-01, -1.55485155e-01,
        1.32187532e+00,  1.57479927e+00, -4.40840839e+00, -8.69561591e-01,
       -6.21292963e-01,  1.59096552e+00, -3.80877975e-01, -3.82820503e-01,
        5.06715542e-01, -1.47192510e+00, -9.49308926e-02, -1.37196356e+00,
        4.98683546e-01,  6.70430961e-01,  3.50567969e+00,  3.20433473e-01,
        4.49176409e-01,  2.93870267e-01, -2.95545050e-01,  9.77906086e-01,
       -1.44652346e+00, -2.74103341e+00,  1.74967671e-01, -3.12111119e-02,
       -6.88327783e-01, -4.53956244e-01, -1.06037264e+00,  4.19889376e-01,
        8.71356372e-01, -

In [26]:
### baseline of dependent and indepedent variable
lr.intercept_

97.3928493679775

In [30]:
## predict the value of home and test it
X_test[0, :]#first row print

array([-1.60278311, -2.03620318, -0.69501761, -1.75532587, -0.60222255,
        0.57140362, -0.46397877, -0.26089606, -1.96893685, -0.18373025,
       -0.1694577 , -0.1466997 , -0.12454231, -0.12160223, -0.12812824,
       -0.12526719, -0.12010681, -0.12526719, -0.11394031, -0.10053942,
       -0.1107353 , -0.1082724 , -0.11551113,  9.30756516, -0.09218776,
       -0.08409599, -0.08923672, -0.08823182, -0.09315135, -0.08923672,
       -0.07975227, -0.0830308 , -0.07749158, -0.08085949, -0.07633675,
       -0.07862985, -0.07749158, -0.07862985, -0.07749158, -0.07862985,
       -0.07862985, -0.07862985, -0.07633675, -0.07749158, -0.07028523,
       -0.07633675, -0.0677166 , -0.0739743 , -0.0751646 , -0.06639573,
       -0.06901264, -0.06901264, -0.0677166 , -0.06901264, -0.0677166 ,
       -0.06639573, -0.05785186, -0.06504853, -0.06639573, -0.06367332,
       -0.06504853, -0.06901264, -0.06504853, -0.06083125, -0.06083125,
       -0.06226825, -0.06639573, -0.06226825, -0.06083125, -0.05

In [32]:
lr.predict([X_test[0, :]])

array([24.52230994])

In [40]:
lr.predict(X_test)

array([ 24.52230994, 125.54854193,  73.39336593, ...,  62.22853087,
        36.29815877,  74.08736658])

In [42]:
y_test

3813     36.29
2623    124.00
5318     67.00
6292    155.00
2354    130.00
         ...  
768     170.00
6591     52.00
4368     74.00
3090     44.80
5017     84.00
Name: price, Length: 1424, dtype: float64

In [44]:
lr.score(X_test,y_test)

0.8038858047649015

In [48]:
from sklearn .linear_model import Ridge, Lasso

In [55]:
rd=Ridge()
rd.fit(X_train,y_train)
rd.score(X_test,y_test)

0.8038373574926921

In [57]:
ls=Lasso()
ls.fit(X_train,y_train)
ls.score(X_test,y_test)

0.7878588118736006

In [59]:
rd1=Ridge(alpha=2)
rd1.fit(X_train,y_train)
rd1.score(X_test,y_test)

0.8037888759042608

In [61]:
ls1=Lasso(alpha=2)
ls1.fit(X_train,y_train)
ls1.score(X_test,y_test)

0.7779323194368201

In [63]:
ls3=Lasso(alpha=3)
ls3.fit(X_train,y_train)
ls3.score(X_test,y_test)

0.7715915018442605

In [65]:
rd3=Ridge(alpha=3)
rd3.fit(X_train,y_train)
rd3.score(X_test,y_test)

0.8037403606763447

In [9]:
import os
print(os.getcwd())


C:\Users\Omkar\Documents\Projects\Banglore house prediction
